//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopDongHo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DatHang_ChiTiet
    {
        [Display(Name = "Mã chi tiết")]
        public int ID { get; set; }

        [Display(Name = "Đơn đặt hàng")]
        [Required(ErrorMessage = "Chưa chọn đơn đặt hàng!")]
        public Nullable<int> DatHang_ID { get; set; }

        [Display(Name = "Điện thoại")]
        [Required(ErrorMessage = "Chưa chọn điện thoại!")]
        public Nullable<int> DongHo_ID { get; set; }

        [Display(Name = "Số lượng")]
        [Required(ErrorMessage = "Số lượng không được bỏ trống!")]
        public Nullable<short> SoLuong { get; set; }

        [Display(Name = "Đơn giá")]
        [Required(ErrorMessage = "Đơn giá không được bỏ trống!")]
        [DisplayFormat(DataFormatString = "{0:N0}", ApplyFormatInEditMode = true)]
        public Nullable<int> DonGia { get; set; }

        public virtual DatHang DatHang { get; set; }
        public virtual DongHo DongHo { get; set; }
    }
}
